##############################################################
# Sample: Vagrant for IOS XE Network Programmability Development
# Author: Hank Preston <hapresto@cisco.com>
#
# ansible_provision.yaml
# Illustrate the following concepts:
# - Provision an IOS XE Device through Ansible
# - Enable NETCONF/RESTCONF APIs and use them
# - Enable Guest Shell
##############################################################
---
- name: Provision IOS XE Devices
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Pause to complete boot
      pause:
        seconds: 5

    - name: Configure NETCONF and RESTCONF
      ios_config:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
        lines:
          - netconf-yang
          - netconf-yang cisco-odm polling-enable
          - restconf
          - ip http server
          - ip http secure-server

    - name: Pause for NETCONF/RESTCONF to start
      pause:
        seconds: 45

#    Ansible 2.4 version of the NETCONF module supports reading in NETCONF Files
    - name: "Generate NETCONF config"
      with_items: "{{interfaces}}"
      template:
        src: "netconf_interface_template.j2"
        dest: "./{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}.xml"

    - name: Configure Interfaces
      with_items: "{{interfaces}}"
      netconf_config:
        host: "{{mgmt_ip}}"
        port: "{{netconf_port}}"
        hostkey_verify: false
        username: "{{username}}"
        password: "{{password}}"
        # xml: |
        #     <config>
        #       <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
        #         <interface>
        #           <name>{{item.interface_type}}{{item.interface_id}}</name>
        #           <description>{{item.description}}</description>
        #           <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
        #           <enabled>true</enabled>
        #           <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
        #             <address>
        #               <ip>{{item.ip_address}}</ip>
        #               <netmask>{{item.subnet_mask}}</netmask>
        #             </address>
        #           </ipv4>
        #         </interface>
        #       </interfaces>
        #     </config>
        #Ansible 2.4 version of the NETCONF module supports reading in NETCONF Files
        src: "./{{inventory_hostname}}-{{item.interface_type}}{{item.interface_id}}.xml"

    - name: Enable IOX
      ios_config:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
        lines:
          - iox

    - name: Pause for IOX to start
      pause:
        seconds: 10

    - name: Configure Interfaces and NAT for Guest Shell
      netconf_config:
        host: "{{mgmt_ip}}"
        port: "{{netconf_port}}"
        hostkey_verify: false
        username: "{{username}}"
        password: "{{password}}"
        src: "guestshell_prep_template.xml"

    - name: Enable Guest Shell
      ignore_errors: true
      ios_command:
        provider:
          host: "{{mgmt_ip}}"
          port: "{{ssh_port}}"
          username: "{{username}}"
          password: "{{password}}"
          timeout: 60
        commands:
          - guestshell enable VirtualPortGroup 0 guest-ip 192.168.35.2 name-server 208.67.222.222
